General:
    comment: 
    seed: 42
    precision: '32'
    epochs: &epoch 200
    grad_acc: 2
    patience: 10
    server: train #train #test
    log_path: logs_zhiliao/

Data:
    dataset_name: lh_data
    data_shuffle: False 
    data_dir: /home/perry/nvme2n1/WMK/zigong/f/ALL_F/
    label_dir: /home/perry/Desktop/Code2/Bca/Data_all/zigongzhiliao/
    fold: 0
    nfold: 5

    train_dataloader:
        batch_size: 1
        num_workers: 16

    test_dataloader:
        batch_size: 1
        num_workers: 16

Model:
    name: ABMIL
    n_classes: 2


Optimizer:
    opt: Adamw
    lr: 0.00005
    opt_eps: null
    opt_betas: null
    momentum: null
    weight_decay: 0.00001

Loss:
    base_loss: CrossEntropyLoss

